apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: my-app
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: test
        image: asia-northeast3-docker.pkg.dev/trans-shuttle-401410/test/test_canary:1.0.0

---
apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: default
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
